// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
// / Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoW-HKczzcOX-F7f8T7sj6bCO8CA-4Uwc',
    appId: '1:659368719051:web:fed80b16583d38c38f214e',
    messagingSenderId: '659368719051',
    projectId: 'userauth-91fa8',
    authDomain: 'userauth-91fa8.firebaseapp.com',
    storageBucket: 'userauth-91fa8.appspot.com',
    measurementId: 'G-KB01W0LQER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPIkvWwaDGMrz2NFM-Wv6l6-nqXLyoRBw',
    appId: '1:659368719051:android:ffc5d14214a5c20c8f214e',
    messagingSenderId: '659368719051',
    projectId: 'userauth-91fa8',
    storageBucket: 'userauth-91fa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkp7ynXgIApV2x_bVE8I8PU4yMauBZwuE',
    appId: '1:659368719051:ios:7972f18ea5b7ecf78f214e',
    messagingSenderId: '659368719051',
    projectId: 'userauth-91fa8',
    storageBucket: 'userauth-91fa8.appspot.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkp7ynXgIApV2x_bVE8I8PU4yMauBZwuE',
    appId: '1:659368719051:ios:7972f18ea5b7ecf78f214e',
    messagingSenderId: '659368719051',
    projectId: 'userauth-91fa8',
    storageBucket: 'userauth-91fa8.appspot.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoW-HKczzcOX-F7f8T7sj6bCO8CA-4Uwc',
    appId: '1:659368719051:web:0ac32705d5b8b57a8f214e',
    messagingSenderId: '659368719051',
    projectId: 'userauth-91fa8',
    authDomain: 'userauth-91fa8.firebaseapp.com',
    storageBucket: 'userauth-91fa8.appspot.com',
    measurementId: 'G-G8TWR58S3C',
  );
}
